#!/bin/sh
cp /media/Kindle/SotongDJ/createlist.py ~/github/launchpad-kindle/createlist.py
cp /media/Kindle/SotongDJ/createlist.sh ~/github/launchpad-kindle/createlist.sh
cp /media/Kindle/SotongDJ/finance.sh ~/github/launchpad-kindle/finance.sh
cp /media/Kindle/SotongDJ/finance.py ~/github/launchpad-kindle/finance.py
cp /media/Kindle/SotongDJ/filter.py ~/github/launchpad-kindle/filter.py
cp /media/Kindle/SotongDJ/file.sh ~/github/launchpad-kindle/file.sh
cp /media/Kindle/SotongDJ/fm.py ~/github/launchpad-kindle/fm.py
cp /media/Kindle/SotongDJ/record.sh ~/github/launchpad-kindle/recor.sh
cp /media/Kindle/SotongDJ/system.py ~/github/launchpad-kindle/system.py
cp /media/Kindle/SotongDJ/changelog.txt ~/github/launchpad-kindle/changelog
cp /media/Kindle/launchpad/SotongDJ.ini ~/github/launchpad-kindle/launchpad/SotongDJ.ini
cp /media/Kindle/mplayer/control.sh ~/github/launchpad-kindle/mplayer/control.sh
cp /media/Kindle/SotongDJ/developer.keystore ~/github/launchpad-kindle/kindlenote/developer.keystore
cp /media/Kindle/SotongDJ/developer.keystore.txt ~/github/launchpad-kindle/kindlenote/developer.keystore.txt
rm -f /media/Kindle/SotongDJ/*~
rm -f ~/github/launchpad-kindle/*~
rm -f /media/Kindle/launchpad/*~
rm -f /media/Kindle/mplayer/*~
